const getFlag = (code) => {
  switch (code) {
    case 4:
      return "fi-af";
    case 8:
      return "fi-al";
    case 10:
      return "fi-aq";
    case 12:
      return "fi-dz";
    case 16:
      return "fi-as";
    case 20:
      return "fi-ad";
    case 24:
      return "fi-ao";
    case 28:
      return "fi-ag";
    case 31:
      return "fi-az";
    case 32:
      return "fi-ar";
    case 36:
      return "fi-au";
    case 40:
      return "fi-at";
    case 44:
      return "fi-bs";
    case 48:
      return "fi-bh";
    case 50:
      return "fi-bd";
    case 51:
      return "fi-am";
    case 52:
      return "fi-bb";
    case 56:
      return "fi-be";
    case 60:
      return "fi-bm";
    case 64:
      return "fi-bt";
    case 68:
      return "fi-bo";
    case 70:
      return "fi-ba";
    case 72:
      return "fi-bw";
    case 74:
      return "fi-bv";
    case 76:
      return "fi-br";
    case 84:
      return "fi-bz";
    case 86:
      return "fi-io";
    case 90:
      return "fi-sb";
    case 92:
      return "fi-vg";
    case 96:
      return "fi-bn";
    case 100:
      return "fi-bg";
    case 104:
      return "fi-mm";
    case 108:
      return "fi-bi";
    case 112:
      return "fi-by";
    case 116:
      return "fi-kh";
    case 120:
      return "fi-cm";
    case 124:
      return "fi-ca";
    case 132:
      return "fi-cv";
    case 136:
      return "fi-ky";
    case 140:
      return "fi-cf";
    case 144:
      return "fi-lk";
    case 148:
      return "fi-td";
    case 152:
      return "fi-cl";
    case 156:
      return "fi-cn";
    case 158:
      return "fi-tw";
    case 162:
      return "fi-cx";
    case 166:
      return "fi-cc";
    case 170:
      return "fi-co";
    case 174:
      return "fi-km";
    case 175:
      return "fi-yt";
    case 178:
      return "fi-cg";
    case 180:
      return "fi-cd";
    case 184:
      return "fi-ck";
    case 188:
      return "fi-cr";
    case 191:
      return "fi-hr";
    case 192:
      return "fi-cu";
    case 196:
      return "fi-cy";
    case 203:
      return "fi-cz";
    case 204:
      return "fi-bj";
    case 208:
      return "fi-dk";
    case 212:
      return "fi-dm";
    case 214:
      return "fi-do";
    case 218:
      return "fi-ec";
    case 222:
      return "fi-sv";
    case 226:
      return "fi-gq";
    case 231:
      return "fi-et";
    case 232:
      return "fi-er";
    case 233:
      return "fi-ee";
    case 234:
      return "fi-fo";
    case 238:
      return "fi-fk";
    case 239:
      return "fi-gs";
    case 242:
      return "fi-fj";
    case 246:
      return "fi-fi";
    case 248:
      return "fi-ax";
    case 250:
      return "fi-fr";
    case 254:
      return "fi-gf";
    case 258:
      return "fi-pf";
    case 260:
      return "fi-tf";
    case 262:
      return "fi-dj";
    case 266:
      return "fi-ga";
    case 268:
      return "fi-ge";
    case 270:
      return "fi-gm";
    case 275:
      return "fi-ps";
    case 276:
      return "fi-de";
    case 288:
      return "fi-gh";
    case 292:
      return "fi-gi";
    case 296:
      return "fi-ki";
    case 300:
      return "fi-gr";
    case 304:
      return "fi-gl";
    case 308:
      return "fi-gd";
    case 312:
      return "fi-gp";
    case 316:
      return "fi-gu";
    case 320:
      return "fi-gt";
    case 324:
      return "fi-gn";
    case 328:
      return "fi-gy";
    case 332:
      return "fi-ht";
    case 334:
      return "fi-hm";
    case 336:
      return "fi-va";
    case 340:
      return "fi-hn";
    case 344:
      return "fi-hk";
    case 348:
      return "fi-hu";
    case 352:
      return "fi-is";
    case 356:
      return "fi-in";
    case 360:
      return "fi-id";
    case 364:
      return "fi-ir";
    case 368:
      return "fi-iq";
    case 372:
      return "fi-ie";
    case 376:
      return "fi-il";
    case 380:
      return "fi-it";
    case 384:
      return "fi-ci";
    case 388:
      return "fi-jm";
    case 392:
      return "fi-jp";
    case 398:
      return "fi-kz";
    case 400:
      return "fi-jo";
    case 404:
      return "fi-ke";
    case 408:
      return "fi-kp";
    case 410:
      return "fi-kr";
    case 414:
      return "fi-kw";
    case 417:
      return "fi-kg";
    case 418:
      return "fi-la";
    case 422:
      return "fi-lb";
    case 426:
      return "fi-ls";
    case 428:
      return "fi-lv";
    case 430:
      return "fi-lr";
    case 434:
      return "fi-ly";
    case 438:
      return "fi-li";
    case 440:
      return "fi-lt";
    case 442:
      return "fi-lu";
    case 446:
      return "fi-mo";
    case 450:
      return "fi-mg";
    case 454:
      return "fi-mw";
    case 458:
      return "fi-my";
    case 462:
      return "fi-mv";
    case 466:
      return "fi-ml";
    case 470:
      return "fi-mt";
    case 474:
      return "fi-mq";
    case 478:
      return "fi-mr";
    case 480:
      return "fi-mu";
    case 484:
      return "fi-mx";
    case 492:
      return "fi-mc";
    case 496:
      return "fi-mn";
    case 498:
      return "fi-md";
    case 499:
      return "fi-me";
    case 500:
      return "fi-ms";
    case 504:
      return "fi-ma";
    case 508:
      return "fi-mz";
    case 512:
      return "fi-om";
    case 516:
      return "fi-na";
    case 520:
      return "fi-nr";
    case 524:
      return "fi-np";
    case 528:
      return "fi-nl";
    case 531:
      return "fi-cw";
    case 533:
      return "fi-aw";
    case 534:
      return "fi-sx";
    case 535:
      return "fi-bq";
    case 540:
      return "fi-nc";
    case 548:
      return "fi-vu";
    case 554:
      return "fi-nz";
    case 558:
      return "fi-ni";
    case 562:
      return "fi-ne";
    case 566:
      return "fi-ng";
    case 570:
      return "fi-nu";
    case 574:
      return "fi-nf";
    case 578:
      return "fi-no";
    case 580:
      return "fi-mp";
    case 581:
      return "fi-um";
    case 583:
      return "fi-fm";
    case 584:
      return "fi-mh";
    case 585:
      return "fi-pw";
    case 586:
      return "fi-pk";
    case 591:
      return "fi-pa";
    case 598:
      return "fi-pg";
    case 600:
      return "fi-py";
    case 604:
      return "fi-pe";
    case 608:
      return "fi-ph";
    case 612:
      return "fi-pn";
    case 616:
      return "fi-pl";
    case 620:
      return "fi-pt";
    case 624:
      return "fi-gw";
    case 626:
      return "fi-tl";
    case 630:
      return "fi-pr";
    case 634:
      return "fi-qa";
    case 638:
      return "fi-re";
    case 642:
      return "fi-ro";
    case 643:
      return "fi-ru";
    case 646:
      return "fi-rw";
    case 652:
      return "fi-bl";
    case 654:
      return "fi-sh";
    case 659:
      return "fi-kn";
    case 660:
      return "fi-ai";
    case 662:
      return "fi-lc";
    case 663:
      return "fi-mf";
    case 666:
      return "fi-pm";
    case 670:
      return "fi-vc";
    case 674:
      return "fi-sm";
    case 678:
      return "fi-st";
    case 682:
      return "fi-sa";
    case 686:
      return "fi-sn";
    case 688:
      return "fi-rs";
    case 690:
      return "fi-sc";
    case 694:
      return "fi-sl";
    case 702:
      return "fi-sg";
    case 703:
      return "fi-sk";
    case 704:
      return "fi-vn";
    case 705:
      return "fi-si";
    case 706:
      return "fi-so";
    case 710:
      return "fi-za";
    case 716:
      return "fi-zw";
    case 724:
      return "fi-es";
    case 728:
      return "fi-ss";
    case 729:
      return "fi-sd";
    case 732:
      return "fi-eh";
    case 740:
      return "fi-sr";
    case 744:
      return "fi-sj";
    case 748:
      return "fi-sz";
    case 752:
      return "fi-se";
    case 756:
      return "fi-ch";
    case 760:
      return "fi-sy";
    case 762:
      return "fi-tj";
    case 764:
      return "fi-th";
    case 768:
      return "fi-tg";
    case 772:
      return "fi-tk";
    case 776:
      return "fi-to";
    case 780:
      return "fi-tt";
    case 784:
      return "fi-ae";
    case 788:
      return "fi-tn";
    case 792:
      return "fi-tr";
    case 795:
      return "fi-tm";
    case 796:
      return "fi-tc";
    case 798:
      return "fi-tv";
    case 800:
      return "fi-ug";
    case 804:
      return "fi-ua";
    case 807:
      return "fi-mk";
    case 818:
      return "fi-eg";
    case 826:
      return "fi-gb";
    case 831:
      return "fi-gg";
    case 832:
      return "fi-je";
    case 833:
      return "fi-im";
    case 834:
      return "fi-tz";
    case 840:
      return "fi-us";
    case 850:
      return "fi-vi";
    case 854:
      return "fi-bf";
    case 858:
      return "fi-uy";
    case 860:
      return "fi-uz";
    case 862:
      return "fi-ve";
    case 876:
      return "fi-wf";
    case 882:
      return "fi-ws";
    case 887:
      return "fi-ye";
    case 894:
      return "fi-zm";
    default:
      return "";
  }
};
export { getFlag };
