name: 26F Studio CI

on:
  push:
    branches: [ main, ci* ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

env:
  HTML_404_URL: https://raw.githubusercontent.com/rafgraph/spa-github-pages/gh-pages/404.html
  DIST_PATH: ./dist/spa
  PACKAGE_PATH: ./spa.zip

jobs:
  build-spa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install packages and build the app
        run: |
          npm install && npm run "spa release"
      - name: Download and modify 404.html for github pages
        if: startsWith(github.ref, 'refs/tags/v') != true
        shell: python3 {0}
        run: |
          import json
          import os
          os.system("wget ${{ env.HTML_404_URL }} -O ${{ env.DIST_PATH }}/404.html")
          with open("${{ env.DIST_PATH }}/index.html", "r", encoding="utf-8") as index_html_file:
            index_html = index_html_file.read()
            index_html = index_html[index_html.find("<title"):index_html.find("</script>",index_html.find("</script>")+1)+9]
          with open("${{ env.DIST_PATH }}/404.html", "r+", encoding="utf-8") as notfound_html_file:
            notfound_html = notfound_html_file.read()
            insert_pos = notfound_html.find("<meta")
            notfound_html = notfound_html[:insert_pos] + notfound_html[notfound_html.find("<script"):]
            notfound_html = notfound_html[:insert_pos] + index_html + notfound_html[insert_pos:]
            notfound_html_file.seek(0)
            notfound_html_file.truncate()
            notfound_html_file.write(notfound_html)
      - name: Deploy to GitHub Pages
        if: startsWith(github.ref, 'refs/tags/v') != true
        uses: crazy-max/ghaction-github-pages@v3
        env:
          GH_PAT: ${{ secrets.FINE_PAT }}
        with:
          build_dir: ${{ env.DIST_PATH }}
          fqdn: dev.studio26f.org
          keep_history: true
          repo: 26F-Studio/26F-Studio.github.io
          target_branch: main
      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/v') != true
        uses: actions/upload-artifact@v3
        with:
          name: 26F-Studio_SPA
          path: ${{ env.DIST_PATH }}
      - name: Deploy to Vercel
        if: startsWith(github.ref, 'refs/tags/v')
        uses: amondnet/vercel-action@v25.1.0
        with:
          scope: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-args: --prod
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Prepare for release
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          7z a -tzip ${{ env.PACKAGE_PATH }} ${{ env.DIST_PATH }}/*
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ env.PACKAGE_PATH }}
