name: Build and Deploy Webpage

on:
  push:
    branches: [ ci-*, main ]
  pull_request:
    branches: [ main ]

jobs:
  get-info:
    runs-on: ubuntu-latest
    outputs:
      branchName: ${{ steps.git-info.outputs.branchName }}
      commitHash: ${{ steps.git-info.outputs.commitHash }}
    steps:
      - uses: actions/checkout@v4
      - name: Get git info
        id: git-info
        shell: bash
        run: |
          BRANCH_NAME=$(git branch --show-current)
          COMMIT_HASH=$(git rev-parse --short ${{ GITHUB.SHA }})
          echo "branchName=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "commitHash=$COMMIT_HASH" >> $GITHUB_OUTPUT

  deploy-github-pages:
    needs: get-info
    runs-on: ubuntu-latest
    env:
      OUTPUT_FOLDER: ./dist/pwa
      PROJECT_NAME: 26F-Studio
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Dependencies and Build
        run: |
          pnpm i
          DEPLOY_GITHUB_PAGE=true pnpm run build
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: ${{ env.OUTPUT_FOLDER }}
          keep_history: false
          target_branch: pages
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}_${{ needs.get-info.outputs.branchName }}_${{ needs.get-info.outputs.commitHash }}_${{ GITHUB.RUN_NUMBER }}_GithubPages
          path: ${{ env.OUTPUT_FOLDER }}/*
