name: 26F Studio CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-spa:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install packages
        run: |
          npm install
      - name: Build the app for development
        run: |
          npm run "spa release"
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist/spa
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 26F-Studio_SPA
          path: dist/spa
